export default {
  "title": "지도 탐색기",
  "type": {
    "title": "유형",
    "cluster": "클러스터",
    "asteroid": "아스테로이드",
  },
  "attribute": {
    "title": "속성",
    "world_trait": "World 특징",
    "biome": "지형",
    "geyser": "간헐천",
    "geyser_output": "간헐천 분출량",
    "geyser_destination": "간헐천 위치",
  },
  "biome": {
    "title": "지형",
    "cold_biome": "추운 지형",
    "hot_biome": "더운 지형",
    "temperate_biome": "Temperate Biome",
    "terra": "테라",
    "swamp": "늪지대",
    "forest": "숲",
    "volcano": "마그마",
    "salt": "소금",
    "desert": "사막",
    "ice": "얼음",
    "ocean": "해양",
    "arid": "아리디오",
    "rust": "녹",
    "badlands": "씨를 맺지 않음",
    "rocky": "암",
    "metallic": "금속",
    "radioactive": "방사능",
    "frozen": "얼음",
    "asteroid": "아스테로이드",
    "vacuum": "진공",
    "space_destination": "우주 목적지",
  },
  "operator": {
    "title": "Operator",
    "at_least": "적어도",
    "at_most": "최대",
    "exactly": "정확히",
  }
}