export default {
  "title": "Map Explorer",
  "type": {
    "title": "Type",
    "cluster": "Cluster",
    "asteroid": "Asteroid",
  },
  "attribute": {
    "title": "Attribute",
    "world_trait": "World Trait",
    "biome": "Biome",
    "geyser": "Geyser",
    "geyser_output": "Geyser Output",
    "geyser_destination": "Geyser Destination",
  },
  "biome": {
    "title": "Biome",
    "cold_biome": "Cold Biome",
    "hot_biome": "Hot Biome",
    "temperate_biome": "Temperate Biome",
    "terra": "Terra",
    "swamp": "Swamp",
    "forest": "Forest",
    "volcano": "Volcano",
    "salt": "Salt",
    "desert": "Desert",
    "ice": "Ice",
    "ocean": "Ocean",
    "arid": "Arid",
    "rust": "Rust",
    "badlands": "Badlands",
    "rocky": "Rocky",
    "metallic": "Metallic",
    "radioactive": "Radioactive",
    "frozen": "Frozen",
    "asteroid": "Asteroid",
    "vacuum": "Vacuum",
    "space_destination": "Space Destination",
  },
  "operator": {
    "title": "Operator",
    "at_least": "at least",
    "at_most": "at most",
    "exactly": "exactly",
  }
}